
name: learn-github-actions
on: [push]
jobs:
  say-hello:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Checkout config scripts
        uses: actions/checkout@v2
        with:
            repository: tsugiproject/tsugi-build
            path: tsugi-build

      - run: cd tsugi-build; bash ubuntu/build-dev.sh
      - run: bash hello.sh

